select DISTINCT OWNER,OBJ_NAME from  dba_audit_object
where owner not in  ('SYS','DBSNMP','FOGLIGHT558','APPDBCONN','BBENZER')
AND TRUNC(TIMESTAMP) > TO_DATE('01/01/2019','MM/DD/YYYY')
GROUP BY OWNER,OBJ_NAME
ORDER BY 1
