SELECT s.SQL_ID, s.SQL_TEXT, s.EXECUTIONS, ss.LAST_ACTIVE_TIME
FROM V$SQL s
JOIN V$SQLSTATS ss ON s.SQL_ID = ss.SQL_ID
WHERE s.EXECUTIONS > 0
AND s.SQL_TEXT LIKE '%UPDATE%'
AND s.SQL_ID = '';




-- EVERY COLUMN
SELECT *
FROM V$SQL s
JOIN V$SQLSTATS ss ON s.SQL_ID = ss.SQL_ID
WHERE s.EXECUTIONS > 0
AND s.SQL_TEXT LIKE '%UPDATE%'
AND s.SQL_ID = '';


--WITH SESSION VIEW ADDED

SELECT s.SQL_ID, s.SQL_TEXT, s.EXECUTIONS, ss.LAST_ACTIVE_TIME, ses.SID
FROM V$SQL s
JOIN V$SQLSTATS ss ON s.SQL_ID = ss.SQL_ID
JOIN V$SESSION ses ON s.PARSING_USER_ID = ses.USER# -- Join on USER# to link the session
WHERE s.EXECUTIONS > 0
AND s.SQL_TEXT LIKE '%UPDATE%'
AND s.SQL_ID = '';
