Select TABLE_NAME, COMPRESSION, COMPRESS_FOR from USER_TABLES
WHERE 1=1
AND COMPRESSION='ENABLED';

Select TABLE_NAME, PARTITION_NAME, COMPRESSION, COMPRESS_FOR from USER_TAB_PARTITIONS
WHERE COMPRESSION='ENABLED';

select TB.TABLESPACE_NAME,TB.DEF_TAB_COMPRESSION,TB.COMPRESS_FOR from  DBA_TABLESPACES tb
where TB.DEF_TAB_COMPRESSION='ENABLED'

